SET TIME ON
SET TIMING ON
SPOOL UPGRADE_SCHEMA.LOG

DEFINE USER_NAME = &&1

SET SERVEROUTPUT ON

PROMPT Username: &&USER_NAME
connect &&USER_NAME/oracle 

PROMPT 
PROMPT Create tables, insert values and create all data view
@upgrade001/main.sql &&USER_NAME
PROMPT

SET SERVEROUTPUT OFF

UNDEFINE USER_NAME
SPOOL OFF