DEFINE USER_NAME = &&1
DEFINE TABLESPACE_NAME = "&&USER_NAME._DATA"
DEFINE TABLESPACE_INDEX = "&&USER_NAME._INDEX"

SET SERVEROUTPUT ON

CREATE TABLE CUSTOMER ( 
  CUSTOMER_ID NUMBER GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 NOT NULL ,
  NAME VARCHAR(500) NOT NULL,
  ADDRESS VARCHAR(500) NOT NULL,
  CONSTRAINT PK_CUSTOMER PRIMARY KEY (CUSTOMER_ID)
  USING INDEX (
      CREATE UNIQUE INDEX CUSTOMER_PK ON CUSTOMER (CUSTOMER_ID ASC)
	  TABLESPACE &&TABLESPACE_INDEX
  )
)
TABLESPACE &&TABLESPACE_NAME;

COMMENT ON COLUMN CUSTOMER.CUSTOMER_ID IS 'Unique identifier';
COMMENT ON COLUMN CUSTOMER.NAME IS 'Name of customer';
COMMENT ON COLUMN CUSTOMER.ADDRESS IS 'Address of customer';

SET SERVEROUTPUT OFF

UNDEFINE USER_NAME
UNDEFINE TABLESPACE_NAME
UNDEFINE TABLESPACE_INDEX