DEFINE USER_NAME = &&1
DEFINE TABLESPACE_NAME = "&&USER_NAME._DATA"
DEFINE TABLESPACE_INDEX = "&&USER_NAME._INDEX"

SET SERVEROUTPUT ON

CREATE TABLE PRODUCT ( 
  PRODUCT_ID NUMBER GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 NOT NULL ,
  NAME VARCHAR(500) NOT NULL,
  PRICE NUMBER(10,5),
  ENERGY_VALUE NUMBER(10,5),
  WEIGHT NUMBER(10,5),
  SHELF_LIFE INT,  
  CONSTRAINT PK_PRODUCT PRIMARY KEY (PRODUCT_ID)
  USING INDEX (
      CREATE UNIQUE INDEX PRODUCT_PK ON PRODUCT (PRODUCT_ID ASC)
	  TABLESPACE &&TABLESPACE_INDEX
  )
)
TABLESPACE &&TABLESPACE_NAME;

COMMENT ON COLUMN PRODUCT.PRODUCT_ID IS 'Unique identifier';
COMMENT ON COLUMN PRODUCT.NAME IS 'Name of product';
COMMENT ON COLUMN PRODUCT.PRICE IS 'Price of product';
COMMENT ON COLUMN PRODUCT.ENERGY_VALUE IS 'Energy valu (kkal/100g)';
COMMENT ON COLUMN PRODUCT.WEIGHT IS 'Weight of product';
COMMENT ON COLUMN PRODUCT.SHELF_LIFE IS 'Shelf life of product (in days)';

SET SERVEROUTPUT OFF

UNDEFINE USER_NAME
UNDEFINE TABLESPACE_NAME
UNDEFINE TABLESPACE_INDEX