DEFINE USER_NAME = &&1
DEFINE TABLESPACE_NAME = "&&USER_NAME._DATA"
DEFINE TABLESPACE_INDEX = "&&USER_NAME._INDEX"

SET SERVEROUTPUT ON

CREATE TABLE STORAGE ( 
  STORAGE_ID  NUMBER GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 NOT NULL,
  BOX_ID INT NOT NULL,
  CELL_ID INT NOT NULL,
  CONSTRAINT PK_STORAGE PRIMARY KEY (STORAGE_ID, CELL_ID)
  USING INDEX (
      CREATE UNIQUE INDEX STORAGE_PK ON STORAGE (STORAGE_ID ASC, CELL_ID)
	  TABLESPACE &&TABLESPACE_INDEX
  ),
  CONSTRAINT STORAGE_FK
    FOREIGN KEY (BOX_ID)
    REFERENCES BOX(BOX_ID)
)

TABLESPACE &&TABLESPACE_NAME;

CREATE INDEX FK_STORAGE_BOX ON STORAGE(BOX_ID ASC) TABLESPACE &&TABLESPACE_INDEX;

COMMENT ON COLUMN STORAGE.STORAGE_ID IS 'Unique identifier';
COMMENT ON COLUMN STORAGE.BOX_ID IS 'Unique identifier of box';
COMMENT ON COLUMN STORAGE.CELL_ID IS 'Unique identifier of cell in storage';

SET SERVEROUTPUT OFF

UNDEFINE USER_NAME
UNDEFINE TABLESPACE_NAME
UNDEFINE TABLESPACE_INDEX