DEFINE USER_NAME = &&1
DEFINE TABLESPACE_NAME = "&&USER_NAME._DATA"
DEFINE TABLESPACE_INDEX = "&&USER_NAME._INDEX"

SET SERVEROUTPUT ON

CREATE TABLE BATCH ( 
  BATCH_ID NUMBER GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 NOT NULL,
  CUSTOMER_ID INT NOT NULL,
  TRANSPORT_ID INT NOT NULL,
  STATUS VARCHAR(500) NOT NULL,
  CONSTRAINT PK_BATCH PRIMARY KEY (BATCH_ID)
  USING INDEX (
      CREATE UNIQUE INDEX BATCH_PK ON BATCH (BATCH_ID ASC)
	  TABLESPACE &&TABLESPACE_INDEX
  ),
  CONSTRAINT BATCH_FK1
    FOREIGN KEY (CUSTOMER_ID)
    REFERENCES CUSTOMER(CUSTOMER_ID),
  CONSTRAINT BATCH_FK2
    FOREIGN KEY (TRANSPORT_ID)
    REFERENCES TRANSPORT(TRANSPORT_ID)
)

TABLESPACE &&TABLESPACE_NAME;

CREATE INDEX FK_BATCH_CUSTOMER ON BATCH(CUSTOMER_ID ASC) TABLESPACE &&TABLESPACE_INDEX;
CREATE INDEX FK_BATCH_TRANSPORT ON BATCH(TRANSPORT_ID ASC) TABLESPACE &&TABLESPACE_INDEX;

COMMENT ON COLUMN BATCH.BATCH_ID IS 'Unique identifier';
COMMENT ON COLUMN BATCH.CUSTOMER_ID IS 'Unique identifier of customer';
COMMENT ON COLUMN BATCH.TRANSPORT_ID IS 'Unique identifier of transport';
COMMENT ON COLUMN BATCH.STATUS IS 'Status of batch (формируется, сформированно, доставляется, доставлено)';

SET SERVEROUTPUT OFF

UNDEFINE USER_NAME
UNDEFINE TABLESPACE_NAME
UNDEFINE TABLESPACE_INDEX