DEFINE USER_NAME = &&1
DEFINE TABLESPACE_NAME = "&&USER_NAME._DATA"
DEFINE TABLESPACE_INDEX = "&&USER_NAME._INDEX"

SET SERVEROUTPUT ON

CREATE TABLE INGREDIENTS ( 
  PRODUCT_ID NUMBER NOT NULL,
  NAME VARCHAR(500) NOT NULL,
  WEIGHT NUMBER(10,5) NOT NULL,
  CONSTRAINT PK_INGREDIENT PRIMARY KEY (PRODUCT_ID, NAME)
  USING INDEX (
      CREATE UNIQUE INDEX INGREDIENT_PK ON INGREDIENTS (PRODUCT_ID ASC, NAME)
	  TABLESPACE &&TABLESPACE_INDEX
  )
)
TABLESPACE &&TABLESPACE_NAME;

CREATE INDEX PK_COMPOSE_ID ON INGREDIENTS(PRODUCT_ID ASC) TABLESPACE &&TABLESPACE_INDEX;
CREATE INDEX PK_COMPOSE_NAME ON INGREDIENTS(NAME ASC) TABLESPACE &&TABLESPACE_INDEX;

COMMENT ON COLUMN INGREDIENTS.PRODUCT_ID IS 'Unique identifier of product';
COMMENT ON COLUMN INGREDIENTS.NAME IS 'Name of ingredient';
COMMENT ON COLUMN INGREDIENTS.WEIGHT IS 'Weight of ingredient';

SET SERVEROUTPUT OFF

UNDEFINE USER_NAME
UNDEFINE TABLESPACE_NAME
UNDEFINE TABLESPACE_INDEX