DEFINE USER_NAME = &&1
DEFINE TABLESPACE_NAME = "&&USER_NAME._DATA"
DEFINE TABLESPACE_INDEX = "&&USER_NAME._INDEX"

SET SERVEROUTPUT ON

CREATE TABLE TRANSPORT ( 
  TRANSPORT_ID NUMBER GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 NOT NULL ,
  TYPE VARCHAR(500) NOT NULL,
  CONSTRAINT PK_TRANSPORT PRIMARY KEY (TRANSPORT_ID)
  USING INDEX (
      CREATE UNIQUE INDEX TRANSPORT_PK ON TRANSPORT (TRANSPORT_ID ASC)
	  TABLESPACE &&TABLESPACE_INDEX
  )
)
TABLESPACE &&TABLESPACE_NAME;

COMMENT ON COLUMN TRANSPORT.TRANSPORT_ID IS 'Unique identifier';
COMMENT ON COLUMN TRANSPORT.TYPE IS 'Type of transport (Свой, Арендован)';

SET SERVEROUTPUT OFF

UNDEFINE USER_NAME
UNDEFINE TABLESPACE_NAME
UNDEFINE TABLESPACE_INDEX