DEFINE USERNAME = &&1
SET SERVEROUTPUT ON

CREATE USER &USERNAME IDENTIFIED BY oracle
       DEFAULT TABLESPACE MMF_2_6_DATA
       QUOTA UNLIMITED ON MMF_2_6_DATA
       QUOTA UNLIMITED ON MMF_2_6_INDEX;
       
ALTER USER &&USERNAME QUOTA UNLIMITED ON MMF_2_6_DATA ; 

SET SERVEROUTPUT OFF

UNDEFINE USERNAME