SET SERVEROUTPUT ON

DELETE FROM INGREDIENTS;
DELETE FROM NUTRITIONS;
DELETE FROM BATCH_INFO;
DELETE FROM BATCH;
DELETE FROM CUSTOMER;
DELETE FROM TRANSPORT;
DELETE FROM STORAGE;
DELETE FROM BOX;
DELETE FROM PRODUCT;

SET SERVEROUTPUT OFF

/*
DROP TABLE &&USER_NAME..INGREDIENTS;
DROP TABLE &&USER_NAME..NUTRITIONS;
DROP TABLE &&USER_NAME..BATCH_INFO;
DROP TABLE &&USER_NAME..BATCH;
DROP TABLE &&USER_NAME..CUSTOMER;
DROP TABLE &&USER_NAME..TRANSPORT;
DROP TABLE &&USER_NAME..STORAGE; 
DROP TABLE &&USER_NAME..BOX;
DROP TABLE &&USER_NAME..PRODUCT;
DROP TABLE &&USER_NAME..RAW_DATA;
DROP VIEW Dolce_Vita
*/